# Generated by Django 4.2.21 on 2026-01-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nama Perusahaan atau Nama Projek', max_length=100)),
                ('logo', models.ImageField(help_text='Upload logo transparan (format PNG/SVG direkomendasikan)', upload_to='projects/logos/')),
                ('description', models.TextField(blank=True, help_text='Deskripsi singkat projek (opsional)', null=True)),
                ('url', models.URLField(blank=True, help_text='Link ke website klien atau detail projek (opsional)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Urutan tampilan (angka kecil muncul lebih dulu)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projek Selesai',
                'verbose_name_plural': 'Daftar Projek Selesai',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
