# Generated by Django 4.2.21 on 2026-01-04 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Penerima')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Nama Perusahaan')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('whatsapp', models.CharField(help_text='Format: 628123456789', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pelanggan',
                'verbose_name_plural': 'Pelanggan',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('template_docx', models.FileField(help_text='Upload template .docx', upload_to='templates/docs/')),
            ],
            options={
                'verbose_name': 'Jenis Surat',
                'verbose_name_plural': 'Jenis Surat',
            },
        ),
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(editable=False)),
                ('formatted_number', models.CharField(editable=False, max_length=100, unique=True)),
                ('subject', models.CharField(max_length=255, verbose_name='Perihal')),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to='generated/pdf/')),
                ('file_docx', models.FileField(blank=True, null=True, upload_to='generated/docx/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='administrasi.customer')),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrasi.documenttype', verbose_name='Jenis Surat')),
            ],
            options={
                'verbose_name': 'Arsip Surat',
                'verbose_name_plural': 'Arsip Surat',
                'ordering': ['-created_at'],
            },
        ),
    ]
