# Generated by Django 4.2.21 on 2026-01-04 11:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GAJI', 'Gaji Karyawan'), ('OPERASIONAL', 'Biaya Operasional'), ('PAJAK', 'Pajak'), ('SEDEKAH', 'Sedekah'), ('LAINNYA', 'Lain-lain')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Pengeluaran',
                'verbose_name_plural': 'Pengeluaran',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('DP', 'Down Payment'), ('LUNAS', 'Pelunasan')], default='LUNAS', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dp_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_paid', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('correspondence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_detail', to='administrasi.correspondence')),
            ],
            options={
                'verbose_name': 'Detail Keuangan Invoice',
                'verbose_name_plural': 'Detail Keuangan Invoice',
            },
        ),
    ]
