# Generated by Django 4.2.21 on 2025-12-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='program_thumbnails/')),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jenis', models.CharField(choices=[('Courses', 'Courses'), ('Services', 'Services')], max_length=20)),
                ('level', models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Advance', 'Advance')], max_length=20, null=True)),
                ('pendaftaran_mulai', models.DateField(blank=True, null=True)),
                ('pendaftaran_tutup', models.DateField(blank=True, null=True)),
                ('pelaksanaan_mulai', models.DateField(blank=True, null=True)),
                ('pelaksanaan_selesai', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
