# Generated by Django 4.2.21 on 2026-01-05 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('thumbnail', models.ImageField(upload_to='services/thumbnails/')),
                ('service_type', models.CharField(choices=[('creative', 'Creative & Design'), ('production', 'Media Production'), ('event', 'Event Management'), ('consultation', 'Konsultasi'), ('development', 'IT Development')], default='creative', max_length=20)),
                ('location_mode', models.CharField(choices=[('online', 'Online/Remote'), ('onsite', 'On-site (Lokasi Fisik)'), ('hybrid', 'Hybrid')], default='online', max_length=10)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_starting_price', models.BooleanField(default=True)),
                ('estimated_duration', models.CharField(blank=True, help_text='Contoh: 3 Hari Kerja atau Per Sesi', max_length=100)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='courses.category')),
                ('managed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_services', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
